[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
dotenvy = "0.15.7"
env_logger = "0.11.5"
envy = "0.4.2"
serde = { version = "1.0.210", features = ["derive"] }
