CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    email VARCHAR COLLATE NOCASE NOT NULL,
    display_name VARCHAR NOT NULL,
    password_hash VARCHAR NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users (email COLLATE NOCASE);

CREATE TABLE IF NOT EXISTS tsumego (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR NOT NULL,
    board VARCHAR NOT NULL,
    tree VARCHAR NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS tsumego_name_unique on tsumego (name);
